name = "proxy"
main = "src/index.mjs"
workers_dev = true
compatibility_date = "2024-07-28"

[placement]
mode = "smart"

[observability]
enabled = false

  [observability.logs]
  enabled = true
  head_sampling_rate = 1
  invocation_logs = true
